my_list = [10, 20, 30, 40, 50]
my_list.append(60)
print("After append:",my_list)
my_list.insert(0, 5)
print("After insert:",my_list)
my_list.remove(30)
print("After remove:",my_list)
my_list.pop(1)
print("After pop:",my_list)
my_list.sort()
print("After sort:",my_list)
my_list.reverse()
print("After reverse:",my_list)
my_list.clear()
print("After clear:",my_list)
print(my_list)
