my_tuple = (10, 20, 30, 40, 50)
print("Tuple:", my_tuple)
print("First element:", my_tuple[0])
print("Last element:", my_tuple[-1])
print("Slice:", my_tuple[1:4])
print("Length:", len(my_tuple))
print("Count of 20:", my_tuple.count(20))
print("Index of 30:", my_tuple.index(30))
print("Max:", max(my_tuple))
print("Min:", min(my_tuple))
print("Sum:", sum(my_tuple))
print("Sorted:", sorted(my_tuple))
print("Reversed:", tuple(reversed(my_tuple)))
print("Converted to list:", list(my_tuple))
print("Converted to set:", set(my_tuple))
print("Converted to dictionary:", dict.fromkeys(my_tuple))
print("Converted to string:", str(my_tuple))